### PR TITLE
feat: add option to ignore commits matching a regexp

### PR DESCRIPTION
**Pull request by lahabana**
Not used to typescript so let me know if any needs to be changed!

### CODE REVIEW

**Review by dimitropoulos — COMMENTED** [review]
thanks!!

some somewhat small changes.  I'd like to keep the `shouldIgnoreCommit` helper function so that we can unit test it, but I see no reason not to keep your new tests, too.

please test your use-case with this code and verify that it works for you.  lemme know what you think!  If you're happy with this I think it can merge and be released immediately.

**Comment by dimitropoulos** [comment]
I guess (news to me) you also have to sign the CLA.. I wonder if there's a way to turn that off...

**Comment by lahabana** [comment]
I'm not sure I follow `shouldIgnoreCommit` still exists it's just a parametrised lambda instead of one that depends on a constant no?

**Comment by dimitropoulos** [comment]
Yep, there's that, but mostly the thing I was thinking of was about keeping it as a separate function and preserving the tests.  Should otherwise work the same!

**Comment by lahabana** [comment]
Ended going some other way closing this

**Pull request closed without merging**
